// <auto-generated />
namespace ACP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class users_in_cars_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users_in_cars_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201509271905361_users_in_cars_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
