// <auto-generated />
namespace ACP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class payment_status_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(payment_status_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201509261800567_payment_status_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
