// <auto-generated />
namespace ACP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class minor_changes_cc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(minor_changes_cc));
        
        string IMigrationMetadata.Id
        {
            get { return "201509261818277_minor_changes_cc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
