// <auto-generated />
namespace ACP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class timespan_changed_in_timepricing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timespan_changed_in_timepricing));
        
        string IMigrationMetadata.Id
        {
            get { return "201509192243436_timespan_changed_in_timepricing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
