// <auto-generated />
namespace ACP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bookings_payments_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookings_payments_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201509261758102_bookings_payments_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
