// <auto-generated />
namespace ACP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class constrainscachngedforaddressinroot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(constrainscachngedforaddressinroot));
        
        string IMigrationMetadata.Id
        {
            get { return "201510040824334_constrainscachngedforaddressinroot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
