// <auto-generated />
namespace ACP.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newfieldsinuser_gende : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfieldsinuser_gende));
        
        string IMigrationMetadata.Id
        {
            get { return "201601211650019_newfieldsinuser_gende"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
